### ISSUE TITLE
System.Exception: 'Handler not found for view ZXing.Net.Maui.Controls.BarcodeGeneratorView.'

### ISSUE THREAD

**Issue by Michal-MK** [julienGrd/BigIslandBarcoding#5]
When I copied the example for rendering a QR code I get this exception.

On MAUI - RC2

**Comment by piepmax** [comment]
You need to add this line to your MauiProgram.cs
` builder.UseBarcodeReader();`

**Comment by Michal-MK** [comment]
Thanks, I thought the reader would only be needed by the reader ;) Maybe this should be specified in the README?

**Comment by umutazazi** [comment]
> 

It is working but this time I got  "'MauiAppBuilder' does not contain a definition for 'UseBarcodeReader' and no accessible extension method 'UseBarcodeReader' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?" error. What should I do ? I can't build because of this error

**Comment by julienGrd** [comment]
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work
